# Account name (canonical) -> Vertical. Source: user-provided list.
# For dual-vertical entries (Geico, Siemens, Siemens Healthineers), first listed vertical is used.
account_to_vertical = {
    "3M Corp": "Manufacturing",
    "AbbVie": "Life Science",
    "Abbott Labs": "Life Science",
    "Adobe": "Technology",
    "Altera": "Technology",
    "Amazon": "Distribution",
    "Amgen": "Life Science",
    "Ball Corporation": "Manufacturing",
    "Bayer": "Life Science",
    "Biogen": "Life Science",
    "Bluerock Therapeutics": "Life Science",
    "Boeing Company": "Manufacturing",
    "Bombardier Learjet": "Manufacturing",
    "Bristol Myers Squibb": "Life Science",
    "CIGNA": "Finance",
    "Capsida Biotherapeutics": "Life Science",
    "Cardinal Health": "Life Science",
    "Charles Schwab": "Finance",
    "Chubb Insurance": "Finance",
    "Citibank": "Finance",
    "Computershare": "Technology",
    "Conduent": "Technology",
    "DP World": "Technology",
    "Deutsche Bank": "Finance",
    "DuPont": "Manufacturing",
    "Elevance Health": "Finance",
    "Eli Lilly LCC/LRL": "Life Science",
    "Fidelity": "Finance",
    "Fuji Film": "Life Science",
    "GE Healthcare": "Manufacturing",
    "GE Power": "Manufacturing",
    "General Dynamics": "Manufacturing",
    "General Electric": "Manufacturing",
    "Geico": "Life Science",  # dual: Life Science, Finance - using first
    "Genentech": "Life Science",
    "Google": "Technology",
    "GXO Logistics": "Distribution",
    "HPE": "Technology",
    "Hewlett-Packard": "Technology",
    "Honda Motor Company": "Automotive",
    "Hyliion": "Manufacturing",
    "IBM": "Technology",
    "Intel": "Technology",
    "IQVIA Biotech": "Life Science",
    "IRG Realty Advisors": "Technology",
    "Johnson & Johnson": "Life Science",
    "JP Morgan Chase": "Finance",
    "Kenvue": "Life Science",
    "LAM Research": "Technology",
    "LinkedIn": "Technology",
    "Lockheed Martin": "Manufacturing",
    "Lonza Biologics": "Life Science",
    "Mars": "Manufacturing",
    "McKesson": "Life Science",
    "Medtronic": "Life Science",
    "Merck": "Life Science",
    "Merck Sodexo": "Life Science",
    "Meta": "Technology",
    "Micron Tech": "Technology",
    "Microsoft": "Technology",
    "MilliporeSigma": "Life Science",
    "Moderna Biotechnology Company": "Life Science",
    "Mp Mask Technology Center": "Technology",
    "Nestle": "Manufacturing",
    "Nike": "Distribution",
    "Northrop Grumman": "Manufacturing",
    "Novartis": "Life Science",
    "NVIDIA": "Technology",
    "Oracle": "Technology",
    "Organon": "Life Science",
    "Parsons Corporation": "Manufacturing",
    "Photronics": "Technology",
    "Piper Aircraft": "Manufacturing",
    "Procter & Gamble Company": "Manufacturing",
    "Sanofi": "Life Science",
    "Scale AI": "Technology",
    "Siemens": "Life Science",  # dual: Life Science, Finance - using first
    "Siemens Healthineers": "Life Science",  # dual - using first
    "Siltronic Corp": "Technology",
    "State Farm Ins": "Finance",
    "T Rowe Price": "Finance",
    "Takeda Pharmaceutical": "Life Science",
    "Tesla Inc - Jacob Reed": "Technology",
    "Texas Instruments": "Technology",
    "Uber": "Technology",
    "Wells Fargo": "Finance",
    "Westinghouse": "Manufacturing",
    # Legacy/CSV-only names kept so existing data still maps
    "Merck CBRE": "Life Science",
    "Boehringer Ingelheim": "Life Science",
    "Gilead Sciences": "Life Science",
    "Pfizer": "Life Science",
    "Thermo Fisher Scientific API": "Life Science",
    "Ford Motor Company": "Automotive",
    "General Motors": "Automotive",
    "Detroit Diesel (DDC)": "Automotive",
    "Delta Air Lines": "Aviation",
    "Textron Aviation": "Manufacturing",
    "Spirit Aerosystems": "Manufacturing",
    "USAA": "Finance",
    "Great American Ball Park": "R&D / Education / Other",
}

# Maps CSV / form variations to canonical account names (must exist in account_to_vertical)
account_name_variations = {
    "Abbvie": "AbbVie",
    "abbvie": "AbbVie",
    "Abbottt": "Abbott Labs",
    "abbottt": "Abbott Labs",
    "Abbott": "Abbott Labs",
    "abbott": "Abbott Labs",
    "3M": "3M Corp",
    "Ball Corp": "Ball Corporation",
    "ball corp": "Ball Corporation",
    "Cigna": "CIGNA",
    "cigna": "CIGNA",
    "Elevance": "Elevance Health",
    "elevance": "Elevance Health",
    "T.Rowe Price": "T Rowe Price",
    "t.rowe price": "T Rowe Price",
    "T.Rowe Price": "T Rowe Price",
    "t rowe price": "T Rowe Price",
    "State Farm": "State Farm Ins",
    "state farm": "State Farm Ins",
    "Adobe Systems": "Adobe",
    "adobe": "Adobe",
    "Lam Research": "LAM Research",
    "lam research": "LAM Research",
    "Eli Lilly LCC/LRL": "Eli Lilly",
    "eli lilly lcc/lrl": "Eli Lilly",
    "eli lilly": "Eli Lilly",
    "IQVIA": "IQVIA Biotech",
    "iqvia": "IQVIA Biotech",
    "Tesla": "Tesla Inc - Jacob Reed",
    "tesla": "Tesla Inc - Jacob Reed",
    "Tesla Inc.": "Tesla Inc - Jacob Reed",
    "GM Milford": "General Motors",
    "gm milford": "General Motors",
    "GM Grand Rapids": "General Motors",
    "gm grand rapids": "General Motors",
    "Grant frazier": "Meta",
    "grant frazier": "Meta",
    "Microsoft Puget Sound": "Microsoft",
    "microsoft puget sound": "Microsoft",
    "Boeing": "Boeing Company",
    "boeing": "Boeing Company",
    "JLL Northrop Grumman": "Northrop Grumman",
    "Wells Fargo-JLL": "Wells Fargo",
    "wells fargo-jll": "Wells Fargo",
    "GE Healthcare - All Sites": "GE Healthcare",
    "ge healthcare - all sites": "GE Healthcare",
    "Johnson & Johnson JLL": "Johnson & Johnson",
    "johnson & johnson jll": "Johnson & Johnson",
    "J&J JLL": "Johnson & Johnson",
    "Nestle - St. Louis": "Nestle",
    "nestle - st. louis": "Nestle",
    "Daimler - Detroit Diesel": "Detroit Diesel (DDC)",
    "daimler - detroit diesel": "Detroit Diesel (DDC)",
    "P&G(JLL)": "Procter & Gamble Company",
    "p&g(jll)": "Procter & Gamble Company",
    "P&G": "Procter & Gamble Company",
    "p&g": "Procter & Gamble Company",
    "Micron (C&W)": "Micron Tech",
    "micron (c&w)": "Micron Tech",
    "Great American Ballpark": "Great American Ball Park",
    "great american ballpark": "Great American Ball Park",
    "Merck Sodexo": "Merck Sodexo",
    "merck sodexo": "Merck Sodexo",
    "Merck CBRE": "Merck CBRE",
    "merck cbre": "Merck CBRE",
    "Merck/CBRE": "Merck CBRE",
    "merck/cbre": "Merck CBRE",
    "Merck/CBRE All Locations": "Merck CBRE",
    "merck/cbre all locations": "Merck CBRE",
    "Takeda (CBRE)": "Takeda Pharmaceutical",
    "takeda (cbre)": "Takeda Pharmaceutical",
    "Honda": "Honda Motor Company",
    "honda": "Honda Motor Company",
    "Gilead": "Gilead Sciences",
    "gilead": "Gilead Sciences",
    "Gilead Oceanside": "Gilead Sciences",
    "gilead oceanside": "Gilead Sciences",
    "BMS": "Bristol Myers Squibb",
    "bms": "Bristol Myers Squibb",
    "BI": "Boehringer Ingelheim",
    "bi": "Boehringer Ingelheim",
    "Altera": "Altera",
    "altera": "Altera",
    "CBRE/Nvidia": "NVIDIA",
    "cbre/nvidia": "NVIDIA",
    "Organon/CBRE": "Organon",
    "organon/cbre": "Organon",
    "Pfizer Memphis": "Pfizer",
    "pfizer memphis": "Pfizer",
    "Lonza JLL": "Lonza Biologics",
    "lonza jll": "Lonza Biologics",
    "Lonza": "Lonza Biologics",
    "lonza": "Lonza Biologics",
    "Genentech HTO": "Genentech",
    "Genentech HIT": "Genentech",
    "Cardinal Helth": "Cardinal Health",
    "Google Bay & San Francisco": "Google",
    "google bay & san francisco": "Google",
    # Nike / GXO / DHL variants
    "Nike/DHL": "Nike",
    "nike/dhl": "Nike",
    "Nike/GXO Relay": "Nike",
    "Nike/GXO Relay (California)": "Nike",
    "nike/gxo relay": "Nike",
    "Nike/GXO Connect": "Nike",
    "Nike/GXO  Connect": "Nike",
    "nike/gxo connect": "Nike",
    "Nike/NALC": "Nike",
    "nike/nalc": "Nike",
    "Nike/Adapt": "Nike",
    "nike/adapt": "Nike",
    "Nike Adapt": "Nike",
    "GXO/Nike": "Nike",
    "GXO/Nike Connect": "Nike",
    "GXO/Nike Relay": "Nike",
    "GXO Nike Relay Bloomington, CA": "Nike",
    "NIKE/DHL Dash": "Nike",
    "DHL/NIKE Dash": "Nike",
    "DHL/NIKE DASH": "Nike",
    "Nike/NALC": "Nike",
    "NIKE/NALC": "Nike",
    "NIKE/ADAPT": "Nike",
    "GXO/NIKE": "Nike",
    "GXO/NIKE Conn ct": "Nike",
    "Relay": "Nike",
    "Connect": "Nike",
    "Omnicom": None,
}
